### ISSUE TITLE
1.19.3 - Says it only works on 1.19.2 is this a misclick?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Numerosityy/CroptopiaAdditions#1]
![24ECkBI 1](https://user-images.githubusercontent.com/10351221/215893053-8fb3750a-cfbc-4a5e-b4fe-6eea1387f66d.png)

**Comment by Numerosityy** [comment]
I'm so sorry, I marked the 1.19.2 version as working with 1.19.3. I hadn't realized how big of a change this was, and I assumed the mod would work on 1.19.3. My apologies
