### ISSUE TITLE
Empty Tags 1.19.2

### ISSUE THREAD

**Issue by xEllierose** [Numerosityy/CroptopiaAdditions#2]
I am on 1.19.2 and these following foods have empty forge tags!
Rice Flour (Empty Tag: forge:grains/rice)
Cola (Empty Tag: croptopia:food_press)
Grape Soda (Empty Tag: croptopia:food_press)

Lemon Lime Soda (Empty Tag: croptopia:food_press)
Orange Sosa comes up as lemon lime soda and also has the (Empty Tag: croptopia:food_press)

Any help would be appreciated, thank you so much for the wonderful mod :)

**Comment by Numerosityy** [comment]
Should be fixed

**Comment by sprocketaudio** [comment]
I found some more of these!

Empty Tag: c:cinnamon
Empty Tag: c:toasts
Empty Tag: c:baked_beans
Empty Tag: c:flour
Empty Tag: c:butters
Empty Tag: c:oranges
Empty Tag: c:lemons
Empty Tag: c:grapes
Empty Tag: c:cherries
Empty Tag: c:crops/rice

Example
![image](https://github.com/Numerosityy/CroptopiaAdditions/assets/13222732/8d150405-368f-4d47-a312-6d2b0e8db530)
![image](https://github.com/Numerosityy/CroptopiaAdditions/assets/13222732/e042cf52-4387-49ef-944a-8b0b915b147c)

V1.19,2 FORGE 2.1
