### ISSUE TITLE
Port to 1.20.1?

### ISSUE THREAD

**Issue by Batimius** [Numerosityy/CroptopiaAdditions#7]
Just like the title says, are you planning on porting the mod over to 1.20.1 forge? (Couldn't find any information anywhere)

**Comment by Numerosityy** [comment]
I'll probably release this soon, at most 5 days

**Comment by Batimius** [comment]
> I'll probably release this soon, at most 5 days

Epic. Thank you very much for the quick reply and support. Truly appreciated!!

**Comment by Numerosityy** [comment]
1.20.1 Release is done! Go check it out!
